### ISSUE TITLE
v121 fails to build with GCC

### ISSUE THREAD

**Issue by Screwtapello** [ares-emulator/ares#1]
Since v121 was... rushed, it turned out Near had made some changes that depended on Clang-specific extensions, preventing it from building with GCC.

@cglmrfreeman has published patches that fix the problem:

https://github.com/cglmrfreeman/Ares-v121-Patch

...but according to the README in that repository:

> Near was obviously trying to tinker with the TLCS900H processor, leaving "still imperfect" in the release notes and what I have done is revert changes to successfully compile. This is a regression of code, and I would like to believe Near was always moving forward to improve their code, and there might have been a reason they wanted to change their code this way, however, I just couldn't figure out how to get it to work in a way Near probably could have.

We'll have to figure out what to do about this.

**Comment by XerTheSquirrel** [comment]
I think for this, there should be an `#if 0` with a comment explaining the situation for each line of change. This way it can be seen which parts are new or different if not immediately fixed.

**Comment by LukeUsher** [comment]
The simple solution, I don't believe we're ready for, but we could just drop support for gcc and require clang as a compiler. Since I know there will be blowback from this, let's consider the alternative.

So there are two separate issues here:

The first is that gcc11 has made `_serialize` a reserved symbol, conflicting with the definition that already existed within ares, fixing this cleanly will be fairly straightforward, we just need to use an alternative symbol name. The patch uses `__serialize` which is still a reserved symbol, due to the double underscore prefix, so I'd like to find a better solution.

The second issue is that Near has refactored the TLCS900H core to be a little cleaner, removing the need for intermediate 'b' or 'w' specifiers, for example, `dmas[0].b.b1` vs `dmas[0].b1`. However, anonymous structs like this are non-standard, so we may just have to live with reverting this change, if we want to continue supporting gcc as a toolchain.

**Comment by Screwtapello** [comment]
Quoting Near in #developers when this `_serialize` issue first came up:

> So we can add `#undef _serialize` to `nall/platform.hpp` where all the gross compiler fixes go

According to that discussion, gcc11's global reservation of`_serialize` is not standards compliant: the compiler reserves *external* symbols matching `_[a-z]*` but this is a member variable so it shouldn't be touched. Because gcc implements it with `#define`, it strictly-speaking oversteps its bounds. But practically speaking we're probably not going to get gcc to change their ways, so maybe an `#undef` really is the nicest way forward here.

Quoting SuperMikeMan in the bcord's #ares channel:

> The TLCS900 one is because anonymous structs are a C11 feature and not a C++ one of any kind, and how they mix with C++ is compiler dependent. Which roughly boils down to Clang lets you mix them and GCC doesn't.

My recollection is that Near would try to follow published standards unless (a) he needed something that just wasn't possible with standards-compliant code, or (b) he felt the standards-compliant version was unbearably ugly. You need to decide for yourself where your boundaries are.

**Comment by LukeUsher** [comment]
Should be resolved as of 11c8185

**Comment by Screwtapello** [comment]
I can confirm lucia now builds on Linux with GCC 10.2.

**Comment by biggestsonicfan** [comment]
Interesting fix to the `_serialize` issue. I hadn't thought of that, and like it much better. Glad to see it up and compiling again! Sorry for the late chime-in here. I've been away for work.
