### ISSUE TITLE
[Feature Request] Specify System Via Command Line Argument

### ISSUE THREAD

**Issue by TheKins** [ares-emulator/ares#101]
It would be nice for those who use front-ends like Launchbox to be able to specify a system to load a game with via a command line argument. Currently, loading .bin files via command line, drag and drop etc. interprets them as Mega Drive ROMs, even when they're another system that commonly uses .bin (in my use case, Colecovision).

Any advice would be great, thanks!

**Comment by LukeUsher** [comment]
Not a bad idea; in the interim you could avoid generic file extensions and use system-specific ones; Colecovision roms should be .col, megadrive should be .md, etc.

**Comment by remutro** [comment]
This was implemented in ares v129. You need to use the --system parameter followed by the system name (hint: name is the same as it is in the menu). 

Since you asked about about two systems, the correct way to use it would be:
ares --system "ColecoVision"   pathto.rom
ares --system "Mega Drive" pathto.rom

**Comment by TheKins** [comment]
Excellent, thank you very much!
