### ISSUE TITLE
[Feature Request] Dynamic search in the load game menu

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#120]
It would be nice if the game list does a dynamic search when typing, instead of the search only happens when the search button (Enter key) is pressed.

**Comment by Kawa-oneechan** [comment]
I should note that for example Windows Explorer doesn't seem to start right away when you type something in the search box. I have plenty folders with a good couple hundred files in, and if it started searching for all files with "s" in, then immediately interrupt that for "su"... I can understand waiting a short time so it can just search only for "super m".

Something you might want to consider.

**Comment by Shideravan** [comment]
The idea was not use any kind of auto-complete. We can perform the search we already have in the emulator, just doing this dynamically.  
![1_QJNf4iiqW0_2DlFD75hnzA](https://user-images.githubusercontent.com/12163923/131204424-5301621c-f47d-4a36-970f-f9a1a5427498.gif)

Of course, you'll have to select the software you like to run, with the keyboard arrows or mouse.
But it's a nice feature to see the list dynamically narrowing to show the thing you're writing in real-time.

**Comment by Shideravan** [comment]
This is a very loose mockup of how it may work. Just ignore the fact that because I need to press [Enter] continually it doesn't seem smooth at all.
https://youtu.be/pX66BeRtIs0

I'm sure that Qt does support dynamic search because QMC2 (a MAME front-end made in Qt) has support for it in his search bar.

**Comment by Kawa-oneechan** [comment]
You seem to misunderstand what I was trying to say, and I misremembered how the search box in Explorer works (though I stand by the point I was trying to make). I think that about evens it out.

**Comment by Shideravan** [comment]
> You seem to misunderstand what I was trying to say, and I misremembered how the search box in Explorer works (though I stand by the point I was trying to make). I think that about evens it out.

Sorry, I am really not understanding what you are trying to say

**Comment by Kawa-oneechan** [comment]
A'ight then.

I thought the search bar in Windows Explorer (_not_ Internet Explorer or Edge, but the _file browser_) worked as I described, writing from memory on my phone. I was wrong, it does not work like that. That was my mistake.

You seem to have mistaken my suggestion for autocomplete. That is not what I had in mind at all. I was thinking of having a big ol' list of files, which the search box filters out. That was your mistake.

So we both made one, y'see?

The _point_ I was trying to make was that immediately starting to find results the very moment you enter the first key may be a bad idea, and that a mild delay would make for a better experience, both for the user and the system. So that instead of starting to search for every single game with an "s" _immediately_ after the user types "s" in the search box, then having to interrupt that and starting over with "su", then again with "sup", it'd make for a better user experience to wait a little bit before committing to the search.

So imagine you type "super mario" at a reasonable speed, and a couple milliseconds after your last keypress it commits to the search and finds all "super mario" games. Conversely, if you type slowly it _would_ return all "s" games, then all "su" games etc.

**Comment by Shideravan** [comment]
No, I didn't mistake it for autocomplete, as you can see in both the gif and the video I posted. Having a delay in searching doesn't make sense when making dynamic searching, if there is a delay it is only because the system is being slow to prefetch the data, not because of a coded delay.

**Comment by Kawa-oneechan** [comment]
Then you still haven't understood my point. I can't make it any clearer than this.

**Comment by sards3** [comment]
What Kawa is talking about is called debouncing.  I don't think it would be necessary in this case though. Even with thousands of files in a directory, filtering should be fast enough that debouncing is not necessary. Windows Explorer's search function could be a counter-example, as it is really slow, but I assume that it's doing something beyond a basic text filter on an in-memory array of filenames.

**Comment by Kawa-oneechan** [comment]
I'm not sure if that's what it's called but I'll take it. And forget Explorer, turned out it didn't do jack squat until I pressed enter.

**Comment by Shideravan** [comment]
Qt has support for this using this: https://doc.qt.io/qt-5/qsortfilterproxymodel.html

**Comment by remutro** [comment]
I know this is old, but this is more complicated for a few reasons. First, Ares does not build/release using Qt by default. It is an option, but it very rarely used and you need to supply Qt5 yourself. So much so that even compiling/linking against Qt was found to be broken for a while and just recently fixed. Very few people run Ares with Qt. 

And in order to implement, this would have to be implemented multiple times in different ways: Win32(Windows), GTK(Linux), Cocoa(MacOS), and in Qt as well. It's quite a bit of work actually.

**Comment by LukeUsher** [comment]
Closing as a wontfix; we don't have control over the operating systems file open dialogs.
