### ISSUE TITLE
[N64] Blast Corps (U): Image flickering in intro

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#125]
In the game Blast Corps, the image is flickering on the title screen. The game doesn't pass to enter in gameplay due the controller pak isn't fully implemented yet, but probably would happens in-game too.

**Comment by remutro** [comment]
Game doesn't play at the correct speed because of issues documented in: https://github.com/higan-emu/ares/issues/14

**PLEASE be aware of this fact as we don't need an additional issue filed for every instance of the same problem in every game.** 

Saves/controller pak/rumble handling is currently insufficiently implemented in Ares, which is why you are seeing this controller pak error. Ares currently decides that if EEPROM, Flash, or SRAM is detected as a save option, then controller 1 will always be set to rumble. If EEPROM, Flash, or SRAM is not being used by the game, then controller 1 will be set to have a controller pak connected. Controllers 2 - 4 always have a rumble pak attached. And there currently isn't any way to change this behavior, or switch between rumble/controller pak in-game. Blast Corps is one game that has a 4Kb EEPROM as well as controller pak and doesn't have support for rumble. 

The list of games impacted is known in the team. Please make sure not to file additional issues like this for each additional game, which requires confirming what type of saves are supported when testing and understanding how controllers pak/rumble selection works (or you can, but they will likely get closed as duplicates :-) ).

**Comment by Shideravan** [comment]
Ok, as the controller pak it's an already known issue, I'll removing this part and keep just the image flickering in the issue description. Thanks you for the heads up :)

**Comment by remutro** [comment]
The controller warnings are fixed as of pull request 156. Game speed/flickering is believed to be caused by issues related to the RDP freeze flag not being properly implemented discussed in issue #14. Not sure if this ticket needs to remain open now if the second half is captured in another issue.

**Comment by Shideravan** [comment]
Ok, issue closed
