### ISSUE TITLE
desktop-ui\emulator\famicom-disk-system.cpp - wrong Famicom Disk System (FDS) firmware hash

### ISSUE THREAD

**Issue by milnak** [ares-emulator/ares#1261]
**Describe the bug**
desktop-ui\emulator\famicom-disk-system.cpp - wrong Famicom Disk System (FDS) firmware hash

**To Reproduce**
Copy FDS bios with hash `fdc1a76e654feea993fcb38366e05ee5f4eb641f86fe6bebaeefd412e112dd72` and set it for FDS - BIOS (Japan).
Running FDS game will fail "firmware is missing or invalid."

```C++
FamicomDiskSystem::FamicomDiskSystem() {
  manufacturer = "Nintendo";
  name = "Famicom Disk System";

  firmware.append({"BIOS", "Japan", "fdc1a76e654feea993fcb38366e05ee5f4eb641f86fe6bebaeefd412e112dd72"});
```
 
**Expected behavior**
It should work

**Screenshots**

**Additional context**
Correct HASH / bios is the rev1 bios:, (99C18490ED9002D9C6D999B9D8D15BE5C051BDFA7CC7E73318053C9A994B0178)

```
Algorithm : SHA256
Hash      : 99C18490ED9002D9C6D999B9D8D15BE5C051BDFA7CC7E73318053C9A994B0178
Path      : D:\temp\fds bios\[BIOS] Family Computer Disk System (Japan) (Rev 1).bin

Algorithm : SHA256
Hash      : FDC1A76E654FEEA993FCB38366E05EE5F4EB641F86FE6BEBAEEFD412E112DD72
Path      : D:\temp\fds bios\[BIOS] Family Computer Disk System (Japan).bin
```

**Comment by LukeUsher** [comment]
mia (the rom loader part of ares) currently relies on a database of hashes to identify the famicom disk system bios, but there is a better way:

All famicom disk system bioses, regardless of the overall hash, contain a trademark security string at offset 0xD37

![image](https://github.com/ares-emulator/ares/assets/740003/37025a54-7550-450a-8b72-135136a37a04)

Fixed as of [dd01cf7](https://github.com/ares-emulator/ares/commit/dd01cf762b23acf0b0806aaeadec45c7fe3e1e76)

Note that this text is encoded in the format used in Super Mario Bros. and Zelda, not plaintext ASCII; which is why I opted for hashing a memory ranger rather than doing a string comparison.
