### ISSUE TITLE
[N64] Jet Force Gemini and Mickey Speedway USA: Crashes in intro

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#129]
The game crashes in the intro, showing the following message
![image](https://user-images.githubusercontent.com/12163923/131249234-f42adfd0-028e-40ef-beeb-7d414d9ca7a4.png)

ares e6948d2

**Comment by Shideravan** [comment]
Another Rareware game with the same crash in intro (the issue is probably related):
![image](https://user-images.githubusercontent.com/12163923/131267183-907ba3d6-0743-4ecb-879d-2b221f8700be.png)

**Comment by remutro** [comment]
Confirmed, both problems are known.

**Comment by kev4cards** [comment]
I reported the Jet Force Gemini crash before in the now-defunct ares repository. In my case with ares v119r2, the error happened at a different point in the intro. Also, the code was different (SP crashed, gfx=802239a0   version 9.6). I believe the problem cleared itself up for a short while between major releases without a known reason as to why or how. It was and still is my understanding that the problem is likely related to RSP timing.

**Comment by Shideravan** [comment]
ares da53c2b
Now it's giving a different code
![image](https://user-images.githubusercontent.com/12163923/133187070-95e3113f-c642-452e-8450-3a644b486b25.png)

But for Mickey's Speedway USA the code is the same as before

**Comment by kev4cards** [comment]
Mickey's Speedway USA has been fixed since commit bcf9cab. Jet Force Gemini remains unchanged,

**Comment by kev4cards** [comment]
Mickey's Speedway USA has regressed back to the way it was as of commit 57b4d68.

**Comment by Shideravan** [comment]
![image](https://user-images.githubusercontent.com/12163923/183164893-4306743f-0bef-451f-9eee-2171d6ea1e88.png)
a new code for Jet Force Gemini in v129 50b2a8f

Mickey's Speedway USA shows the same code
![image](https://user-images.githubusercontent.com/12163923/183170455-df667665-b6fe-41a2-95af-0b3908b5c906.png)

**Comment by loganmc10** [comment]
This happens in m64p as well. I notice that the game sets the SSTEP (single step) bit right around when this happens.

It doesn't look like Ares implements single step mode for the RSP, I think MAME has an implementation of it, but I'm not sure if it's correct.

**Comment by loganmc10** [comment]
After looking into this a bit, I think the RSP just be going into single step mode in order to print that debugging message. It seems like the problem starts when the CPU sets SIG0 (requesting the RSP to yield). If I shorten the RSP timing in m64p, the yield is never requested, and the video never freezes. So it may just be a general CPU/RSP timing issue

**Comment by invertego** [comment]
These games contain the following timing test which fails unless PI DMA and RSP pipeline stalls are emulated very precisely. The value in `a1` is a loop counter used in a busy wait for PI DMA completion. The Zelda games contain the same code, though they manifest different errors when the test fails.

```
06c  srl     v1,a1,12
070  subi    v0,v1,$4c
074  bltz    v0,$cc
078  subi    v0,v1,$4f
07c  bgtz    v0,$cc
```

With recent (#1147) and upcoming (#1149) changes, ares will have sufficiently accurate timing to pass this test.

**Comment by Ryan-Myers** [comment]
> These games contain the following timing test which fails unless PI DMA and RSP pipeline stalls are emulated very precisely. The value in `a1` is a loop counter used in a busy wait for PI DMA completion. The Zelda games contain the same code, though they manifest different errors when the test fails.
> 
> ```
> 06c  srl     v1,a1,12
> 070  subi    v0,v1,$4c
> 074  bltz    v0,$cc
> 078  subi    v0,v1,$4f
> 07c  bgtz    v0,$cc
> ```
> 
> With recent (#1147) and upcoming (#1149) changes, ares will have sufficiently accurate timing to pass this test.

Sorry for reviving something a year old, but do you know where in the ROM of JFG this assembly occurs? I'm investigating JFG with a [decompilation project](https://github.com/Ryan-Myers/Jet-Force-Gemini) and I can't seem to find that snippet of code. It's entirely possible it's hard for me to find it due to differences in disassembly, so it might help if you could provide more details as to where in the ROM this code occurs.

**Comment by invertego** [comment]
@Ryan-Myers Offset 0x9FEBC in the retail USA ROM. Here it is again with the instruction bytes:

```
06c  00051b02  srl     v1,a1,12
070  2062ffb4  subi    v0,v1,$4c
074  04400015  bltz    v0,$cc
078  2062ffb1  subi    v0,v1,$4f
07c  1c400013  bgtz    v0,$cc
```
