### ISSUE TITLE
[N64] Michael Owens WLS 2000 (E): Crashes the emulator immediatelly

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#136]
The emulator crashes immediatelly when try to load this game.
Windows 10 x64
ares e6948d2

**Comment by bigbass1997** [comment]
Hmm I can't reproduce. Using the linux build of v123. Both the European and US versions do not crash.

**Comment by Shideravan** [comment]
> Hmm I can't reproduce. Using the linux build of v123. Both the European and US versions do not crash.

For the US version you mean Mia Hamm's Soccer 64, right? Mia Hamm's Soccer 64 has no issues for me, just the European version.
The issue only happens in Michael Owens WLS 2000 (E). I tried with different dumps and the problem always happens. Maybe is related with the Windows version.

**Comment by Shideravan** [comment]
I tested with the official ares 123 release and the issue happens too.
MD5 of the different roms tested.
312B7449D7C9227FF4C1945B94A68ABA  Michael Owen's WLS 2000 (Europe).zip
AA451044641D7AEB94A33E891D0AD592  Michael Owen's World League Soccer 2000 (Europe).n64
892222CC4BAF9958405D20BC492175BF  Michael Owen's WLS 2000 (Europe).z64

**Comment by bigbass1997** [comment]
> 892222CC4BAF9958405D20BC492175BF Michael Owen's WLS 2000 (Europe).z64

This matches mine. Can confirm it appears to be related to Windows. Tried it in a Win10 VM (linux host), and the game does appear to freeze or otherwise crash (just a black screen). The emulator program itself does not crash though.

**Comment by remutro** [comment]
My experience matches Shideravan's post. This game causes the ares executable to crash when starting with an access violation (0xC0000005).

**Comment by remutro** [comment]
This is the info gdb spits out at me when it crashes:

Thread 36 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 26976.0xf28]
0x00007ff77e3c0da8 in ares::Nintendo64::VI::refresh (this=0x7ff77f36f420 <ares::Nintendo64::vi>) at ../ares/n64/vi/vi.cpp:94
94	          target[x] = source[x * 4 + 0] << 16 | source[x * 4 + 1] << 8 | source[x * 4 + 2] << 0;

The code here is dealing with the Vulkan layer. Looks like we are getting a bad value back here from parallel-rdp resulting in invalid address lookups.

Edit: After talking to bigbass1997, we realized his experience is different because running Windows in a VM means no vulkan for you. Those video drivers don't have vulkan support so if the problem is indeed related to the parallel-rdp project or Ares interfacing with it then this would explain the difference.

**Comment by remutro** [comment]
Based on my testing with issue: https://github.com/ares-emulator/ares/issues/254 - this game does not crash when video settings are set to HD or UHD. It only crashes when resolution is set to SD. So there is a workaround.

Issue #254 is exactly the same as this issue, just with a different game. Issues should likely be merged referencing both games.

**Comment by Shideravan** [comment]
Merged issues with #254 as requested because both seems to be very related
