### ISSUE TITLE
[Documentation] Near is not present on the Credits page.

### ISSUE THREAD

**Issue by MisterSheeple** [ares-emulator/ares#159]

**Comment by Shideravan** [comment]
Where's Near reference is missing? He's in ares "about" section
![image](https://user-images.githubusercontent.com/12163923/132252811-c0ab01e3-b621-4218-96d3-5da5cd733eed.png)

Ps.: I think it's fair to include Luke Usher name there too, as he is the current person responsible for the project :)

**Comment by bigbass1997** [comment]
Since they said "Credits page", I'm guessing they are talking about this https://ares-emulator.github.io/credits. In which case, they are right, Near's name isn't on that page.

**Comment by Shideravan** [comment]
Thanks for the info. Yeah, that's right. Surely Near deserves the credits there too.

**Comment by MisterSheeple** [comment]
> Ps.: I think it's fair to include Luke Usher name there too, as he is the current person responsible for the project :)

Agreed.



> Thanks for the info. Yeah, that's right. Surely Near deserves the credits there too.

Thank you!

**Comment by remutro** [comment]
Likely an oversight because this page (and all pages) were originally taken from https://ares.dev/credits. This was originally maintained by Near, and they wouldn't have credited themselves originally. The page is just a copy, it's just different in this context now. It was Near crediting others who helped them getting Ares to where it is today. Just keep the context in mind. 

Fully agree though that Near should probably be added here now. I think it is more then fair that Luke adds their name as well given their significant contributions and willingness to lead/continue the project.

**Comment by LukeUsher** [comment]
Regarding the about box; I wanted to keep Near's name in there out of respect due to the history of ares, and the majority of the work being from them.

I opted for 'ares team' over my own name, due to it primarily becoming a community project at this point.

Regarding the website, I'm open for suggestions on how to credit Near; it wouldn't fit in any of the existing categories so we'd likely have to create a new heading.

**Comment by bigbass1997** [comment]
> Regarding the website, I'm open for suggestions on how to credit Near; it wouldn't fit in any of the existing categories so we'd likely have to create a new heading.

Not sure what header to use, but it should be somewhere at the top. For the content, something like this should work: "Near - Creator of higan and ares." I feel that may not be enough to do his work justice, but it's a start.

**Comment by hadess** [comment]
As a lurker, and Luke can remove this comment if it's too out-of-topic, Near was non-binary and used the they/them pronouns. I understand that English pronouns can be difficult to use, and that not everyone is a native speaker, but attention to details would be appreciated.

**Comment by Screwtapello** [comment]
My understanding is that Near experimented with identifying as non-binary, but eventually decided that pronouns weren't important to them and moved on. I appreciate that people want to respect Near's wishes, and that gender identity is important to a lot of people, but gender identity wasn't particularly important to Near — certainly not as important as game preservation, or stopping online harassment.

**Comment by remutro** [comment]
The credits page no longer exists in the updated website. Near is credited in the about box of the application itself. Not sure if anything else is needed right now, or this issue can be closed as it doesn't appear as if they are purposely being excluded.

**Comment by MisterSheeple** [comment]
I think you're right. I'll go ahead and close this.
