### ISSUE TITLE
[Suggestion] Determine a fixed day for the official relases (MAME releases style)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#222]
Now that ares has become a community project, publicizing it has become more important than ever!
Thus new collaborators can integrate the project and ensure that it is alive and with constant developments.
A factor that has been relevant for the project's dissemination in various channels has been the official release of each stable version, where several places talk about ares and show reports of improvements compared to previous versions.

A few examples of communication channels that covers the ares releases:
https://www.reddit.com/r/emulation/comments/owlthu/ares_v122_has_just_been_released/
https://gbatemp.net/threads/ares-multi-system-emulator-version-118-release.583380/
https://www.youtube.com/watch?v=cRec5YSDecU
https://www.youtube.com/watch?v=oavAIY7jOsI
https://youtu.be/mxmaQgqkOhE?t=811

That said, according to with was discussed in Discord, as of today we still don't have a formal day for ares releases. It usually happens when it is felt that the emulator "has made enough progress" or that "it's been a while without a new release". But this seems to be completely subjective.
But there are some options that ares can use for this.
MAME as an example defined to release new versions every last Wednesday of the month (unless the code ares broken at that point, which causes the release to be postponed). Maybe this kind of approach is a good idea for ares: eg. release the first Thursday of every month, except when an exception happens (the code is broken, there are not many improvements in the code that justifies a new release yet, etc.)
What do you think about it?

**Comment by Max833** [comment]
I think your dedication to this project is fantastic and very helpful, but something like this would only create too much pressure on the developers. You can download the nightly build whenever you want. This should be enough. ^^
https://github.com/higan-emu/ares/releases/tag/nightly

**Comment by Shideravan** [comment]
The problem is not about the nightly build availability (I normally build by myself to test at every commit anyway, as it normally gives me much more performance on my end when doing the builds using _lto=false_).
If we have a fixed day for release would be nice, as I said, to further better spread the word about the project.
That's something we want - the flame of the project remains alive and always strong for the community.
If it seems like a lot of work/pressure for Luke to do this monthly, I'm willing to be responsible for these official releases, no problem :)

**Comment by bigbass1997** [comment]
Why does it have to have a scheduled release date, just to publicize the project? I feel it would be far more effective to make an announcement when a new release is actually available, rather than to say there is one coming soon which people may forget about. Can you not already spread the word about Ares at any time? Why does it have to only be on a specific day?

Plus, I completely agree with what Max833 said that creating a fixed release date will put far too much pressure on developers. There's never a guarantee that new features/changes/compatibility will exist, or be ready, after any given amount of time. Different developers contribute different kinds of changes, at different rates. And if someone wants the newest updates, they can just grab a nightly build any time they want.

**Comment by Kawa-oneechan** [comment]
I've nothing to add but a nod of agreement at @Max833 and @bigbass1997.

**Comment by LukeUsher** [comment]
Yeah this isn't happening; it's not too unusual for some emulation projects to go multiple months without significant improvements, and also have small periods of intense activity.

A strict release schedule doesn't really fit into this workflow.
