### ISSUE TITLE
[Discussion] Ares and crash dumps

### ISSUE THREAD

**Issue by BiZkViT96** [ares-emulator/ares#265]
If Ares crashed, Windows will create crash dump, and its can be big. Check your SSD/HDD: C:\Users\NAME\AppData\Local\CrashDumps
![2021-10-23 23_14_48-TreeSize Free](https://user-images.githubusercontent.com/88586431/138607513-a1109d2a-2ca7-4afa-982e-63722ceb7e3c.png)

**Comment by remutro** [comment]
Ares, like any application, is going to produce a crash dump according to the settings you have defined. If your system is configured to generate a full memory dump, then it is going to create a crash dump that represents all memory in use at the time of the crash for that process. You can reduce this footprint by configuring your system to take minidumps, but it is far less useful to devs. It will record stack traces and a few other things, but minidumps exclude all memory associated with the executable which is where the majority of size comes from. Ares is literally no different then any application in this regard. I'm not sure what resolution the original poster is looking for. Obviously crashes are no good, but if you have a reproducible problem then outline them in your issue request. If you don't want them to be so large, you can configure your system to take minidumps, but it's less useful for devs. Please also include the rom (and hash), version of ares, any saves states, or any additional steps to reproduce the crash and it will be investigated. There are a few already that are known, and you should look at the issues list to make sure this isn't a new issue.

Again, ares isn't unique in regards to crash dumps. These settings are system wide on Windows, and size depends on how much memory the process was using at the time of the crash.

**Comment by invertego** [comment]
User mode crash dumps are not enabled by default in Windows. Possibly you have installed some software that enabled them. Instructions for changing these settings can be found here:

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

If you want to turn them off completely, you can delete the LocalDumps key mentioned on that page.

Also worth pointing out: the size of an ares crash dump can be much larger than the amount of physical memory it was using at the time due to the way memory for JIT caches is reserved.

**Comment by LukeUsher** [comment]
I'm closing this issue; these crash dumps are not generated by ares itself, but by your operating system.

Obviously, ares shouldn't crash, but if it does, you should create a bug ticket for the crash, including what game you were playing (with hashes), and other relevant details.
