### ISSUE TITLE
Rename lucia to "ares" for releases.

### ISSUE THREAD

**Issue by Screwtapello** [ares-emulator/ares#29]
For historical reasons, ares' user-interface is called "lucia", and is built as `lucia.exe` (on Windows). However, the public name of the project is "ares", and since the default build only produces a single executable, it might as well be named `ares.exe`.

It's probably not globally replacing `lucia` with `ares` across the source-code and filenames (not least because there's already an `ares` directory in the repo), but it should be easy to rename the executable in the GitHub release scripts and in the `make install` script.

**Comment by Screwtapello** [comment]
An example of the end-user confusion this causes: https://www.reddit.com/r/emulation/comments/owlthu/ares_v122_has_just_been_released/h7m5d9c/

**Comment by Kawa-oneechan** [comment]
Very Yes.

**Comment by LukeUsher** [comment]
On the basis that there is currently only the ares user interface, how about properly rebranding 'lucia' to 'ares', and renaming the 'lucia' directory to 'desktop-ui', as well as updating config/setting paths to use 'ares' over 'lucia'

This provides a few benefits

1. It is obvious that desktop-ui is the desktop/pc UI for ares. lucia is a far less obvious name. This also allows alternative UIs in future, such as android or iOS, or even web (via emscripten) or console ports that we can name them accordingly. 
2. The executable name/package name is what users expect, they download 'ares' so to show as 'lucia' in the menu system could be confusing
3. Settings/configuration is stored in an 'ares' directory, rather than a 'lucia' directory, this avoids confusion when end-users may not be aware of what 'lucia' is.

It would be sad to lose the naming scheme inherited from Near, but this would be more practical going forward, imo.

I'm open to suggestions/feedback.

**Comment by Kawa-oneechan** [comment]
*Very* Yes.

**Comment by LukeUsher** [comment]
resolved as of 189487a2cadf4c6243e44015918c67b1f995b817
