### ISSUE TITLE
Option to individual controller setting (per system)

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#30]
It's annoying every time when I choose a system to play (p.g colecovision that has some different button layout wich I like to put the numbers in the keyboard's num pad) and change the system (p.g. Nintendo 64) and all the buttons has changed.
Would be nice to have both general controls but the system itself doesn't change the key from each system individually,

**Comment by LukeUsher** [comment]
Ares uses a single 'virtual gamepad' for controls, the 'console-specific' mapping pages in the UI are for convenience, but ares was never designed to support multiple mapping/per-console mappings.

This was one of the many things that was done to make ares easier to use than higan, but I can see why people would want this.

It might take a significant rework to the core/take some time to implement, but it's certainly possible.

**Comment by Shideravan** [comment]
Agreed. Just don't think that this approach is really becoming usability "easier" for all the users, as the user needs to change the configs everytime it changes the system. Some projects such MAME ou even Retroarch have a default control configuration but also per-system configuration and even the most newbie user can understand this concept easily in those projects.

**Comment by Shideravan** [comment]
Also, I don't think that the names of the buttons in the Virtual Gamepad does much to avoid confusion. Maybe renaming the buttons there to Action 1, Action 2, Action 3, Shoulder Left 1, Shoulder Right 2 rather than ABCXYZLR as each letter means different positions and uses across different systems (eg. X in a XBox controller means is placed at left side and never is used as an confirmation button, in the Playstation family it's in bottom and generaly is used as an ocidental confirmation button, X in SNES is the upmost position and in GameCube is at right position) and of course, the number pad that exists in some systems such Colecovision doesn't make much sense to be default mapped in the same position of traditional buttons and the 2 action buttons being in the Start Select.
I'll take a look and see if I can submit at least this change for now, that will certainly help to avoid some confusions until someone implement a per-system support in the control system.

**Comment by LukeUsher** [comment]
Regarding button names: the ares UI itself tells you that the mapping is based on the layout of an Xbox controller; there shouldn’t be any confusion there. 

This also matches the virtual gamepad functionality of other emulators such as retroarch.

**Comment by Shideravan** [comment]
Well, there are no buttons such as C, Z, Select, L1, L2, R1, R2 in the default Xbox controller. Also, it's good to exist more buttons there, such as Numpad buttons for ColecoVision and potential future drivers, such as Jaguar, Atari 5200, Intellivision. etc. This way we don't need to worry about them misconfiguring the other more "traditional" buttons in different drivers. Some consoles and peripherals also include different buttons and layouts, but afaik the base input is already thought to easily add more inputs as the project goes on (and of course, it becomes increasingly difficult to group all the commands basing only on the default Xbox controller layout).
I'm not even nearly as a "huge fan" of RetroArch to say the truth, but they not only have different categories in the default controllers but also have visual icons to represent every button, not only the letter itself. Also afaik these base display is configurable. I usually prefer to base the default controller in PlayStation layout for example (with L1, L2, Select, etc).
Anyway, I already made the modifications (including more default keys for better represent the ColecoVision Numpad) but I'm just waiting for a more stable version of the code to test properly before commit (https://github.com/higan-emu/ares/issues/38).
I think we can discuss better about these details in the commit itself.

**Comment by FitzRoyX** [comment]
Ares is designed under the notion that:

-Most people don't have 20 retro controllers hooked up to their PC
-Most people don't have encyclopedic knowledge of old controllers like Coleco to even make these decisions manually
-Most people don't want to spend 45 minutes setting up an emulator
-Most systems actually have fairly straightforward translations to a modern pad and setup would feel repetitious (FC,GB,GBC,GBA,SNES,MS,GG,PS1)


Yes, there are some bizarro layouts like Wonderswan and Coleco that make translation to modern pads difficult, but it's not like the scheme we pick is "wrong" or unworkable. We just do our best. It's not like people are passionately fighting about N64 C buttons being on the shoulders vs the right thumbstick or whatever. It's just a matter of dealing with the hand you're dealt to avoid being bogged down with configuration instead of playing games. There is no shortage of people complaining about RetroArch or MAME's configuration hell.

I don't entirely agree with how Ares handles this either. I think the recent change have system dropdowns attempting to show every button from every system has made things less straightforward and more tedious. It used to be that it displayed every button on the pad you were using, not just what was available on the particular dropdown selection. So if you setup the NES first, then go play some SNES games, your XY mappings are empty because the NES dropdown didn't have those buttons to display. You should ideally not have to return to the input settings multiple times depending on what systems you decide to play first.

**Comment by Shideravan** [comment]
> Ares is designed under the notion that:
> 
> -Most people don't have 20 retro controllers hooked up to their PC
> -Most people don't have encyclopedic knowledge of old controllers like Coleco to even make these decisions manually
> -Most people don't want to spend 45 minutes setting up an emulator
> -Most systems actually have fairly straightforward translations to a modern pad and setup would feel repetitious (FC,GB,GBC,GBA,SNES,MS,GG,PS1)
> 
> Yes, there are some bizarro layouts like Wonderswan and Coleco that make translation to modern pads difficult, but it's not like the scheme we pick is "wrong" or unworkable. We just do our best. It's not like people are passionately fighting about N64 C buttons being on the shoulders vs the right thumbstick or whatever. It's just a matter of dealing with the hand you're dealt to avoid being bogged down with configuration instead of playing games. There is no shortage of people complaining about RetroArch or MAME's configuration hell.
> 
> I don't entirely agree with how Ares handles this either. I think the recent change have system dropdowns attempting to show every button from every system has made things less straightforward and more tedious. It used to be that it displayed every button on the pad you were using, not just what was available on the particular dropdown selection. So if you setup the NES first, then go play some SNES games, your XY mappings are empty because the NES dropdown didn't have those buttons to display. You should ideally not have to return to the input settings multiple times depending on what systems you decide to play first.

The updates that I'm doing in the controller mapping have all these factors in mind. Like: You don't will use a console with Numpad? No problem, just leave it blank and focus on what you'll need. I already made my mind it's really not a good idea to use only generic names as "Button 1, Button 2..." (as in MAME) or even "Action 1, Action 2..." as I commented before. And uses Z, C, etc. don't helps either, as most of users don't even have something similar in their gamepads. 
But when checking with some users and studying some controller layouts, it seems that a button position makes more sense and is more consistent across different kinds of hardware. This universally makes much more sense, as "Shouder Left Button (Top)" than "L1" for example. Don't need to have a Dual Shock to know what you're representing. And it easily translate as a L in SNES control pad, in L1 in Dual Shock, in a LB in XBox 360 controller.
I'm also thinking to put some tooltips about what every button mean, in a future update, to be even more clear to the most newbie.
By the way, somebody knows if Qt does support images as a tooltip (and if there is an easy way to integrate that in the input menu)?

**Comment by Shideravan** [comment]
I'll close this for now, as I'm already working on (at least part of) the solution. And I feel that the commit post itself is a better place for us to discuss this.

**Comment by Shideravan** [comment]
I'll close this for now, as I'm already working on (at least part of) the solution. And I feel that the commit post itself is a better place for us to discuss this.

**Comment by kathyrollo** [comment]
Mentioning #173 here for historical and documentation purposes.

**Comment by rrrcabral** [comment]
I need that too.
Already on the second console that I decided to use Ares I noticed that it ruined the configuration of the previous console.
and now that I want to use Ares for a third console (as it is the most compatible, congratulations) I know that I will encounter a stressful situation of seeing that the new settings for this system will ruin the previous ones, and I suspect that I will have to abort the use of Ares and use another specific emulator for this third console.

[ just SEO words to help people find this issue: ares controllers multiple system ]

**Comment by rrrcabral** [comment]
I think the emulator should already come with a 'virtual gamepad' already configured. When it detects an Xbox controller, for example, it already configures everything for that controller. There are emulators with this Auto-Mapping.

Because I find it very confusing that Ares changes a button in one system and it automatically changes in another. You have to keep trying to figure out which is the most correct and coherent button between different systems, and there are systems that can be contradictory. That's why the emulator should already come with a default virtual gamepad configured. Since the author sees logic in this unifying buttons between systems, he certainly knows which is the ideal button between different systems. Leaving it up to the user to find out breaks the excuse that this unification exists to "make it easier for the user."

**Comment by neotins** [comment]
I have NES, SNES, Genesis, N64 and Xbox style controllers all available to be used on my PC. The lack of separate controller support per system is a killer for me. As one of the top emulators available, I'm surprised that something like this was overlooked. Hopefully they'll add this in at some point, but until then, I'll have to use something else.
