### ISSUE TITLE
[Request] CHD support

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#31]
Would be nice if the CD based systems had CHD file support. It's one of the best format for preservation and are used alredy in emulators such MAME, Duckstation, Redream, etc.

**Comment by LukeUsher** [comment]
I do understand the love for the CHD format, however, it is not a good fit for ares: mostly because the dependencies it brings in are huge: it requires a flac decoder, zlib and an lzma.

You'll notice that generally, ares does not use external dependencies and we would like to keep it that way, and implementing the required components and a custom CHD decoder is a huge task, the time is better spent improving emulation.

The CHD format also has had some pretty nasty 'gotchas' that emulators have had to work around (CHD aligns sectors on different boundaries than they would be on a real disc, and the emulator has to compensate for this, which is non-obvious unless you study the MAME CD-ROM implementation)

CHDv5 (the current version) is also unsuitable for storing subchannel data (so PAL PS1 games with libcrypt will require separate .sbi files regardless), and is known to have issues with some Sega CD games (this will all be fixed in CHDv6, as far as I'm aware)

**Comment by LukeUsher** [comment]
Closing as wontfix for now, but feel free to re-open once CHDv6 has been finalized, and we'll consider our options then. Hopefully by that point, ares will be much further along in terms of completeness/compatibility for cd-rom based systems too.

**Comment by Shideravan** [comment]
Ok, makes sense to wait for CHD v6 specifications first, as most of these issues may be addressed and we (hopefully) don't have to wait too much for this release

**Comment by LukeUsher** [comment]
Update: CHD is supported for cd-rom systems as of https://github.com/ares-emulator/ares/commit/75c0a5f36e455aa0147e1ce747d2b28cf698f52e
