### ISSUE TITLE
[NGP/NGPC] Support for bioses in No-Intro .ngp format

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#34]
Currently, only the TOSEC Firmware set works.

**Comment by Screwtapello** [comment]
So far as I can tell, TOSEC describes the NGP BIOS as:

    <rom
      name="SNK Neo-Geo Pocket BIOS (1998)(SNK)(en-ja).bin"
      size="65536"
      crc="6232df8d"
      md5="d87d876c4391935c9d48ef352a3ff02d"
      sha1="2f6429b68446536d8b03f35d02f1e98beb6460a0"/>

Meanwhile, the No-Intro Dat-O-Matic says:


<table>
<tr><th>File:</th><td>[BIOS] SNK Neo Geo Pocket (Japan, Europe).ngp</td></tr>
<tr><th>Size:</th><td>65536</td></tr>
<tr><th>CRC32:</th><td>6232DF8D</td></tr>
<tr><th>MD5:</th><td>D87D876C4391935C9D48EF352A3FF02D</td></tr>
<tr><th>SHA-1:</th><td>2F6429B68446536D8B03F35D02F1E98BEB6460A0</td></tr>
</table>

Both files have the same size, and the same hashes, they're both in the same format. The only difference is that TOSEC uses the generic `.bin` extension, while No-Intro has renamed it to the technically-incorrect `.ngp` extension (the BIOS isn't an NGP *cartridge*, so it shouldn't be `.ngp`).

Short answer: just rename the file to `bios.bin` and it'll work.

Long answer: Near was always against supporting No-Intro's attempts at faux-consistency (like treating BIOS images as though they were game cartridges, or treating the Campus Challenge cart as four individual games instead of one game with four files), but maybe in the name of making life easier for end-users it's time to change that?

**Comment by meowthed** [comment]
We could do that, but we have to wait until whoever's leading this project to have a say.

**Comment by LukeUsher** [comment]
Personally, I don't understand why it's not working; the hash is the same, and ares shouldn't care about the file extension when you specify a bios file.

I will look into it, but it really should be working already: I use the ngp extension myself.

**Comment by LukeUsher** [comment]
Closing this as I can't reproduce; No-Intro bios files have worked fine for me since day-1.
