### ISSUE TITLE
BIOS setup is tedious

### ISSUE THREAD

**Issue by FitzRoyX** [ares-emulator/ares#36]
Problem:
-manually setting up bios filepaths for this many systems takes a long time
-has to be repeated if the cfg is wiped
-requires GUI code

Proposed behavior:
Include "Firmware" folder in release packages. On rom load, check if that system's cfg bios filepath is empty or invalid. If so, scan ares/firmware/ for that system's bios (by hash, not filename).

Users can drag bios files en masse into that folder.

**Comment by LukeUsher** [comment]
I can see this being useful, but I wouldn't say it's a high priority because I don't think this will impact most users; the most likely use case is people setup each system as/when they first play a game for that system

I think the chances of people setting up every single bios up-front is one that will rarely occur in practice, except perhaps among some dedicated testers.

I do think we should look into this, though: simplifying configuration/setup is never a bad thing, as long as it doesn't impact functionality.

**Comment by Shideravan** [comment]
I agreed about the hash verification, as it avoid that bad dumps or incompatible formats being used as the BIOS files (even the name is correct). It's surely something that can avoid emulation errors.

> Problem:
> -manually setting up bios filepaths for this many systems takes a long time
> -has to be repeated if the cfg is wiped
> -requires GUI code
> 
> Proposed behavior:
> Include "Firmware" folder in release packages. On rom load, check if that system's cfg bios filepath is empty or invalid. If so, scan ares/firmware/ for that system's bios (by hash, not filename).
> 
> Users can drag bios files en masse into that folder.

**Comment by Shideravan** [comment]
If you're not liking it, why you can't remake it youself and we check if we like it?
When somebody try to improve something in the interface you just run to complain.

**Comment by birdybro** [comment]
You'd be surprised how many users of multi-system emulators just get a pre-configured zip of all the bios files you need and dump it somewhere simple. It may not come up for single-system emulators, but multi-system emulators and frontends (MiSTer, retroarch, mednafen, etc...) all have plenty of these kinds of all in one bios zips out there. I think it's more popular nowadays to do the readymade zips of bios files than it is to individually go looking for specific ones, one at a time. 

Just my two cents coming from helping many people setup their MiSTer FPGA's, their Retroarch setups, and their Mednafen setups frequently... the vast majority of them prefer the script (in the case of the MiSTer there is an unofficial script) that grabs all of the BIOS files for them automatically, or downloading a zip with everything, instead of manually finding the right BIOS and placing it there.

**Comment by dracc** [comment]
@birdybro I don't think catering to pirates is a big motivation for an emulator developer. Is quite a good way to get DCMA strikes and the like.

**Comment by birdybro** [comment]
Respectfully speaking, I don't think there has been any evidence of DMCA strikes as a result of having a "firmware" folder or "system" folder against Retroarch and Mednafen. MAME too has a method where you just put a bios.zip into the /mame/roms/ folder, which has been around since the 90's, and no DMCA claims for this reason against it. I don't consider this a valid concern. Reasons for DMCA strikes against emulators on github:

https://github.com/github/dmca/commit/fca0a199638d85b3563318c63c7db01376a7dd53 - Javascript emulator with pre-loaded copies of Nintendo games rewritten in Javascript apparently.

https://torrentfreak.com/nintendo-shuts-down-javascript-gameboy-emulator-150712/ - They previously took a variation of it down for the exact same reason, and it was the same emulator again redistributing their IP.

Having a presumed folder structure where BIOS files are placed and scanning for them is not anywhere near the justifications given for DMCA claims in the past on github. 

Patreon is another example. They took down RPCS3's Patreon page because Atlus DMCA'd them because people could play Persona 5 on the PS3 emulator. That same exact DMCA, if the platform listens to the request, could be used on every single emulator of anything, it could be used on Higan right now, Ares, WINE even. That DMCA request had nothing to do with where the firmware folder is and how the emulator looks for firmware that the user may or may not put there.

ROM sites were taken down by DMCA for obvious reasons, so I don't think I have to go into that. Those DMCA strikes are irrelevant to where a firmware folder is located or how firmware files that are placed there by the user are scanned.

I understand the concern over DMCA in general because it's heavy-handed and draconian in most situations, but I think it's not relevant to my feedback or this issue specifically.

**Comment by LukeUsher** [comment]
Improved/fixed in 703e2ea
