### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#38]
I'm receiving `collect2.exe: error: ld returned 1 exit status mingw32-make: *** [GNUmakefile:69: all] Error 1` in the code of the version `7adfece`.

Windows 10 x64
gcc (MinGW) 8.1.0

**Comment by LukeUsher** [comment]
I can’t reproduce this locally, or on the CI server, it builds correctly in both cases. 

I have seen this error once before though on my old computer with ares v119; it happened because I was running out of ram during the linking phase. 

What command are you using to build? If you’re passing any options such as -jN, consider reducing the value of N to spawn less worker threads. 

If even without the -j option, consider “make lto=false”. This will harm performance slightly at runtime, but will require less resource during the linking phase.

**Comment by Shideravan** [comment]
Compiled fine with `mingw32-make lto=false` in the latest version. Thanks :)
