### ISSUE TITLE
[NeoGeo] Needs documentation on getting games to work

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#42]
So far with my tests, I have only gotten so far as showing a bios message. Using MAME-compliant ZIPs.

**Comment by LukeUsher** [comment]
Neo Geo MVS does not work yet, and only a small handful (1-5 at most) of games work in AES mode. There’s a reason the Neo Geo core only has a 1 star compatibility / completeness rating

**Comment by cjalbert** [comment]
As Luke pointed out, this core is very early in development. Only AES is supported, and you will need to additionally supply the AES BIOS file along with the MAME compatible zips of the games. 

7 games in the library boot and are reasonably playable, and zero games have sound. Much more work is needed on this core. So you don't waste more time experimenting, these are the games that should boot and can be played:

Sonic Wings (Aero Fighters) 2
Captain Tomaday
Metal Slug Super Vehicle-001
Minansan no Okagesamadesu! Dai Sugoroku Taikai
Puzzle De Pon!
Quiz Daisousa Sen - The Last Count Down
Quiz King of Fighters

These games boot and are playable to a lesser degree due to additional issues that need to be resolved:

Sonic Wings (Aero Fighters) 3
Aggressors of Dark Kombat
Breakers
Crossed Swords 2 (bootleg of CD version)
Far East of Eden - Kabuki Klash
Goal! Goal! Goal!
King of Fighters '94, The
Magician Lord
Neo Turf Masters
Ragnagard
Savage Reign
Voltage Fighter - Gowcaizer

There are a few additional games that will boot to title/menus, but won't get any further, but for the most part any other NeoGeo game at this point in time does not work.

**Comment by LukeUsher** [comment]
Closing this as it's not a documentation issue; it's purely that the Neo Geo core is still highly experimental and most games don't work yet.
