### ISSUE TITLE
[SG-1000] Public Domain homebrew issues

### ISSUE THREAD

**Issue by meowthed** [ares-emulator/ares#51]
Arno Dash - Stuck at level load.
![Arno Dash (PD) v1 00 under4mhz 2020-07-23 2021-08-11 10-29-34](https://user-images.githubusercontent.com/41223243/128961180-25f15c7b-8ec2-4497-8ab0-2ee464da1521.png)

Bacachase - Green screen.
![Bacachase (PD) nitrofurano 2016-10-25 2045 2021-08-11 10-29-53](https://user-images.githubusercontent.com/41223243/128961229-d6aca2b0-1288-462c-a7a5-bbe2c4b49323.png)

CMJN - Works, with glitches throughout.
![CMJN (PD) nitrofurano 2014-06-22 2021-08-11 10-35-43](https://user-images.githubusercontent.com/41223243/128961288-a66c59f1-5dc1-467d-955c-baee48f805ef.png)

H7N9 - Works, but idk if it's graphics corruption.
![H7N9 (PD) nitrofurano 2016-10-24 2021-08-11 10-32-15](https://user-images.githubusercontent.com/41223243/128961324-d84a4056-798f-4ada-92a0-d819116ace80.png)

Jet Paco & Jet Puri - White screen for both NTSC and PAL versions.
![Jet Paco   Jet Puri NTSC (PD) v1 00 Mojon Twins 2019-01-08 2021-08-11 10-31-54](https://user-images.githubusercontent.com/41223243/128961343-4d84a02c-9ea0-4378-8f1c-a0792491a85a.png)

Nyan Cat Demo - Blue screen with a white square.
![Nyan Cat Demo (PD) v0 01 nitrofurano 2021-08-11 10-37-29](https://user-images.githubusercontent.com/41223243/128961449-6747fe0a-81a6-4d6e-89ae-6341b3131de2.png)

Omikuji - White screen with a black rectangle.
![Omikuji (PD) v1 Maechio 2021-08-11 10-37-42](https://user-images.githubusercontent.com/41223243/128961473-bb25efc4-1d29-406b-82ac-be30096d6120.png)

Pole Position Remake - Works, but idk if it's graphics corruption.
![Pole Position Remake (PD) nitrofurano 2016-04-10 1925 2021-08-11 10-38-03](https://user-images.githubusercontent.com/41223243/128961505-698bb1e9-b9c3-43b1-a5a1-4bcc6c6471c1.png)

S_Sniper - Stuck at title screen with high hz buzzing sound.
![S_Sniper (PD) v1 Maechiko 2021-08-11 10-38-20](https://user-images.githubusercontent.com/41223243/128961564-9e8eac14-f1cd-40a9-aa28-ed58321b3136.png)

Suepr UWOL - White screen.
![Suepr UWOL (PD) Mojon Twins 2016-11-19 1411 2021-08-11 10-38-50](https://user-images.githubusercontent.com/41223243/128961569-b81ac830-90f3-4cf2-8cb4-63f8ea2f553a.png)

**Comment by invertego** [comment]
A couple of these are real emulation bugs, one of them is borderline (similar issues might occur on real hardware), and several are simply not emulation bugs at all.

### Emulation bugs

- Jet Paco & Jet Puri - White screen for both NTSC and PAL versions.
Fixed by ad51e37
- Super UWOL - White screen.
Fixed by ad51e37

These roms are > 32 KiB in size, which ares currently doesn't support. Some published games were this large, so this really ought to be supported.

### Borderline emulation bugs

- Nyan Cat Demo - Blue screen with a white square.
Fixed by #54 

This demo requires VRAM to be initialized to zero (or at least not all FF).

### Not emulation bugs

- Arno Dash - Stuck at level load.

I was able to reproduce this on version 1.00 of this homebrew but not on version 1.03. Both versions are downloadable [here](https://www.smspower.org/Homebrew/ArnoDash-SG). It seems to be a game bug that was fixed.

- Bacachase - Green screen.

This game requires > 2 KiB  of system RAM to function (see references to $C800 [in the source](https://www.smspower.org/Homebrew/Bacachase-SG)). The SG-1000 only has 1 KiB of memory, and consequently it only works on the Master System, which has 8 KiB of RAM. It works fine on ares if loaded as a Master System ROM.

- CMJN - Works, with glitches throughout.
- H7N9 - Works, but idk if it's graphics corruption.
- Pole Position Remake - Works, but idk if it's graphics corruption.

These have the same issues on other emulators, so I'm inclined to believe they would look no better on real hardware.

- Omikuji - White screen with a black rectangle.
- S_Sniper - Stuck at title screen with high hz buzzing sound.

These are actually miscategorized Master System homebrew. They work fine if you load them as Master System ROMs.

**Comment by invertego** [comment]
I believe ad51e37 and #54 took care of everything that wasn't demonstrably a game bug.

**Comment by meowthed** [comment]
closed as per latest changes.
