### ISSUE TITLE
[32X] Star Wars Arcade(U): Black screen

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#52]
The game doesn't boot, freezing in a black screen before anything shows up.
Version: e14b01f
OS: Windows 10 x64

**Comment by remutro** [comment]
I might as well add this here. The Ares team is aware of all games/issues in the 32X library at the moment. Here is a breakdown of known issues.

These games currently don't boot:
After Burner
BC Racers
Metal Head
Star Wars Arcade
WWF Raw

Brutal & NBA Jam Tournament Edition will hang at some point due to using a cached interpreter by default (they work if compiled in full interpreter mode).

Doom & Primal Rage has missing sound effects.

FIFA Soccer 96 has some graphics corruption with the stands in the north-east part of the field

Virtua Racing Deluxe sees slight graphics corruption during intro screens.

WWF Wrestlemania has corrupt menus, missing sprites, and missing characters and is unplayable.

Zaxxon has missing polygons and sprites and doesn't scroll the background and as a result is unplayable. 

Motocross Championship, NFL Quarterback Club, & Virtua Fighter have noticeable audio corruption.

Finally, there is something with the core where some games lose audio after playing other 32X games. This sometimes requires restarting Ares to correct (Kolibri & Brutal seem especially susceptible to this).

**Comment by Shideravan** [comment]
Closing due a better coverage in https://github.com/higan-emu/ares/issues/180
