### ISSUE TITLE
[GBA] All "Game Boy Advance Video" carts doesn't pass "not compatible with GBA Player" screen

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#59]
All the games of the GBA Video series (https://en.wikipedia.org/wiki/Game_Boy_Advance_Video) don't pass after the following screen.

![image](https://user-images.githubusercontent.com/12163923/129635567-59a1b6d7-c911-41c4-b1f0-3883f937da5e.png)

Version tested: `cb4a79e`
Windows 10 x64

**Comment by Screwtapello** [comment]
But they still proceed to the main menu and let you play the videos, right?

**Comment by Shideravan** [comment]
> But they still proceed to the main menu and let you play the videos, right?

Nope. They don't pass this screen.

**Comment by Shideravan** [comment]
I changed the title of this issue because I forgot that the same message appears even in GBA running normally, but just pass on. But it's not the case in ares right now, as it hangs on this screen.

**Comment by Screwtapello** [comment]
It looks like ares' desktop UI is hard-coded to always load GBA games in Game Boy Player mode:

https://github.com/higan-emu/ares/blob/189487a2cadf4c6243e44015918c67b1f995b817/desktop-ui/emulator/game-boy-advance.cpp#L60

That makes sense since the desktop UI is aggressively simplified, and GBP mode is neutral or an improvement for actual games, it's only these video carts that cause problems. I expect this was very deliberate on Near's part, since he expected people who wanted niche software like this to use higan or mGBA or something. However, higan has stalled and ares is still under development, so it may be time to revisit that decision.

**Comment by LukeUsher** [comment]
Fixed as of faa4f18, by emulating 'Game Boy Advance' rather than 'Game Boy Player'
